
// Mock data for test series
export const mockTestSeries = [
  {
    id: "test1",
    title: "Basic Mathematics",
    description: "Fundamental mathematics concepts including arithmetic, algebra, and geometry.",
    price: 20,
    isPurchased: true,
  },
  {
    id: "test2",
    title: "General Knowledge",
    description: "Test your knowledge on a variety of general knowledge topics.",
    price: 20,
    isPurchased: false,
  },
  {
    id: "test3",
    title: "English Grammar",
    description: "English language proficiency test focusing on grammar and usage.",
    price: 20,
    isPurchased: false,
  },
  {
    id: "test4",
    title: "Science Fundamentals",
    description: "Basic concepts from physics, chemistry, and biology.",
    price: 20,
    isPurchased: false,
  },
];

// Mock data for questions
export const mockQuestions = [
  {
    id: "question1",
    questionText: "What is 2 + 2?",
    options: {
      a: "3",
      b: "4",
      c: "5",
      d: "6",
    },
    correctAnswer: "b",
    explanation: "Basic addition: 2 + 2 = 4",
    testSeriesId: "test1",
    subject: "Mathematics",
  },
  {
    id: "question2",
    questionText: "What is the capital of India?",
    options: {
      a: "Mumbai",
      b: "New Delhi",
      c: "Kolkata",
      d: "Chennai",
    },
    correctAnswer: "b",
    explanation: "New Delhi is the capital city of India.",
    testSeriesId: "test2",
    subject: "Geography",
  },
  {
    id: "question3",
    questionText: "Which of these is a correct sentence?",
    options: {
      a: "He don't like coffee.",
      b: "She don't like tea.",
      c: "They doesn't like milk.",
      d: "I don't like sugar.",
    },
    correctAnswer: "d",
    explanation: "The correct form is 'don't' for I, you, we, they and 'doesn't' for he, she, it.",
    testSeriesId: "test3",
    subject: "Grammar",
  },
  {
    id: "question4",
    questionText: "What is the square root of 16?",
    options: {
      a: "2",
      b: "4",
      c: "8",
      d: "16",
    },
    correctAnswer: "b",
    explanation: "The square root of 16 is 4, since 4 × 4 = 16.",
    testSeriesId: "test1",
    subject: "Mathematics",
  },
  {
    id: "question5",
    questionText: "Which planet is known as the Red Planet?",
    options: {
      a: "Venus",
      b: "Mars",
      c: "Jupiter",
      d: "Saturn",
    },
    correctAnswer: "b",
    explanation: "Mars is known as the Red Planet due to its reddish appearance.",
    testSeriesId: "test2",
    subject: "Astronomy",
  },
  {
    id: "question6",
    questionText: "What is the past tense of 'run'?",
    options: {
      a: "Runned",
      b: "Ran",
      c: "Running",
      d: "Runs",
    },
    correctAnswer: "b",
    explanation: "'Ran' is the past tense of 'run'. 'Running' is the present participle.",
    testSeriesId: "test3",
    subject: "Grammar",
  },
  {
    id: "question7",
    questionText: "If x + 3 = 7, what is the value of x?",
    options: {
      a: "3",
      b: "4",
      c: "5",
      d: "10",
    },
    correctAnswer: "b",
    explanation: "x + 3 = 7, so x = 7 - 3 = 4.",
    testSeriesId: "test1",
    subject: "Mathematics",
  },
  {
    id: "question8",
    questionText: "Which gas do plants absorb from the atmosphere?",
    options: {
      a: "Oxygen",
      b: "Carbon Dioxide",
      c: "Nitrogen",
      d: "Hydrogen",
    },
    correctAnswer: "b",
    explanation: "Plants absorb carbon dioxide from the atmosphere during photosynthesis.",
    testSeriesId: "test4",
    subject: "Biology",
  },
  {
    id: "question9",
    questionText: "What is the chemical symbol for gold?",
    options: {
      a: "Go",
      b: "Gd",
      c: "Au",
      d: "Ag",
    },
    correctAnswer: "c",
    explanation: "Au (from Latin 'aurum') is the chemical symbol for gold.",
    testSeriesId: "test4",
    subject: "Chemistry",
  },
  {
    id: "question10",
    questionText: "Which of these is NOT a primary color?",
    options: {
      a: "Red",
      b: "Blue",
      c: "Green",
      d: "Yellow",
    },
    correctAnswer: "d",
    explanation: "In the RGB color model, red, green, and blue are primary colors. Yellow is a secondary color.",
    testSeriesId: "test4",
    subject: "Physics",
  },
];
